# -*- coding: utf-8 -*-
"""FGS/MIT/2021/034.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jL8H_KEtrzzDa_Fp8W7W7NoLkM9v8UDF
"""

import csv
# Empty list 
bikeList=[]

# Function to create bike
def createBike():

    print("_______________ Adding Bikes _________________")
    has=False
    make = input("make:")
    model = input("model:")
    try:
        units = int(input("units: "))
        price = float(input('price: '))
    except:
        print("Enter numerical values only")

    bike = {'make': make, 'model': model, 'units': units, 'price': price}

    for i in bikeList:
        if make.lower()==i['make'].lower() and model.lower() == i['model'].lower():
            has=True
            break

        else:
            has = False

    if has==True:
        print('Bike already  in the inventory')


    else:
        bikeList.append(bike)
        print("Added bike")



# to check bike price

def checkBike():
    print("_______________ Check Price of a Bikes _________________")
    bikeMake = input("make: ")
    bikeModel = input('model: ')
    for i in bikeList:
        if bikeMake.lower() == i['make'].lower() and bikeModel.lower() == i["model"].lower():
            print('Price of the bike = ',i["price"])
            break

# To sell bike

def sellBike():
    print("_______________ Selling  Bikes _________________")
    bikeMake = input("make: ")
    bikeModel = input('model: ')

    for i in bikeList:
        if bikeMake.lower() == i['make'].lower() and bikeModel.lower() == i["model"].lower():
            print('Number of available units :',i['units'])
            numberOfBikes = int(input("Number of bikes want to purchase: "))
            x=int(i['units'])
            y=float(i["price"])

            while True:
                if numberOfBikes<= x:
                    x=x - numberOfBikes
                    bill = y * numberOfBikes
                    print("You bought: ", i['make'], " - ", i['model'])
                    print(f"Your bill = {bill}")
                    i['units']=x
                    break

                else:
                    print('Out of Stock')
                    break


            print('Available units of ', i['make'], i['model'],  '=', i["units"])
            break



# To get inventory
def getInventory():
    print("_______________ Inventory _________________")
    for i in bikeList:
        print('Make | Model | Units | Price')
        print(i['make'],'\t', i['model'], '\t', i['units'],'\t', i['price'])
        print("______________________________________________________")



# Read abc.csv file to bikelist as dictionary to store data
def readFile():
    with open('abc.csv','r') as rFile:
        r=csv.DictReader(rFile)
        for line in r:
            bikeList.append(line)

# Write bike list as dictionary
def writeFile():
    fields = ['make', 'model', 'units','price']
    with open('abc.csv','w') as wFile:
        w=csv.DictWriter(wFile,fieldnames=fields,delimiter=',')
        w.writeheader()
        w.writerows(bikeList)

# To run all methods
def mainFunction():
    while True:

        try:
            print('___________________________________________')
            print(" Enter 1 to add item to list. "
                  "\n Enter 2 to check price. "
                  "\n Enter 3 to sell item. "
                  "\n Enter 4 to check inventory. "
                  "\n Enter 5 to exit")
            opt=int(input("Select your option:"))


            if opt==1:
                createBike()


            elif opt==2:
                checkBike()


            elif opt==3:
                sellBike()

            elif opt==4:
                getInventory()


            elif opt==5:
                break

            else:
                print('Invalid input')

        except:
            print("Enter numerical values")


readFile()
mainFunction()
writeFile()

